name: fablemaker
adopt-info: fablemaker-source
summary: Interactive stories where you can customize characters, texts and sounds!
base: core22
architectures:
- amd64
confinement: strict
grade: stable
issues: https://github.com/kenvandine/fablemaker-snap/issues
contact: https://github.com/kenvandine/fablemaker-snap/issues

apps:
  fablemaker:
    extensions: [gnome]
    command: Fablemaker_v32_Lin/Fablemaker_32.x86_64
    desktop: com.endlessnetwork.fablemaker.desktop
    common-id: com.endlessnetwork.fablemaker.desktop
    plugs:
      - audio-playback
      - joystick
      - network

parts:
  fablemaker:
    source: https://github.com/endless-network/Fablemaker_Binary/releases/download/v1.2/Fablemaker_v32_Lin.zip
    plugin: dump
    override-prime: |
      craftctl default
      chmod +x $CRAFT_PRIME/Fablemaker_v32_Lin/Fablemaker_32.x86_64
  fablemaker-source:
    source: https://github.com/endless-network/Fablemaker_Binary/archive/refs/tags/v1.2.tar.gz
    plugin: dump
    parse-info: [com.endlessnetwork.fablemaker.appdata.xml]
    override-pull: |
      craftctl default
      sed -i 's|Icon=com.endlessnetwork.fablemaker$|Icon=${SNAP}/meta/gui/icon.png|g' $CRAFT_PART_SRC/com.endlessnetwork.fablemaker.desktop
      sed -i 's|Exec=com.endlessnetwork.fablemaker.sh$|Exec=fablemaker|g' $CRAFT_PART_SRC/com.endlessnetwork.fablemaker.desktop

      mkdir -p $CRAFT_PART_INSTALL/meta/gui
      cp FM_Favicon_128x128.png $CRAFT_PART_INSTALL/meta/gui/icon.png
